services:
  app:
    build: .
    container_name: solution_factory_app
    command: sh -c "
      python manage.py makemigrations
      && python manage.py migrate
      && gunicorn app.wsgi:application --bind 0.0.0.0:8000
      "
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    depends_on:
      - solution_factory_pg
    restart: always
  solution_factory_pg:
    env_file:
      - .env.prod
    image: postgres:12-alpine
    container_name: solution_factory_pg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
volumes:
  postgres_data: